// ThinkingPhrases.swift — Stage-specific status phrases with spinner animation
//
// Ships with ~50 built-in phrases across stages.
// Custom phrases loaded from .junco/phrases.json (generated by background task).
// Spinner uses braille dot animation. Phrases shown in red below prompt.

import Foundation

/// Provides thinking/status phrases for each pipeline stage.
public struct ThinkingPhrases: Sendable {
  public static let spinnerFrames = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]

  private static let builtin: [String: [String]] = [
    "classify": [
      "Reading intent",
      "Understanding",
      "Parsing query",
      "Classifying",
      "Interpreting",
    ],
    "strategy": [
      "Choosing approach",
      "Weighing options",
      "Strategizing",
      "Considering paths",
      "Evaluating",
    ],
    "plan": [
      "Planning steps",
      "Breaking down",
      "Mapping work",
      "Decomposing",
      "Sequencing",
    ],
    "execute": [
      "Working",
      "Executing",
      "Processing",
      "Applying changes",
      "Making progress",
      "Transforming",
      "Iterating",
      "Computing",
      "Resolving",
      "Synthesizing",
    ],
    "read": [
      "Reading code",
      "Scanning file",
      "Loading context",
      "Parsing source",
      "Inspecting",
    ],
    "edit": [
      "Editing code",
      "Rewriting",
      "Modifying",
      "Patching",
      "Refining",
    ],
    "write": [
      "Writing code",
      "Generating",
      "Composing",
      "Drafting",
      "Creating",
    ],
    "bash": [
      "Running command",
      "Executing shell",
      "Processing",
      "Building",
      "Compiling",
    ],
    "search": [
      "Searching",
      "Scanning codebase",
      "Grepping",
      "Finding matches",
      "Locating",
    ],
    "reflect": [
      "Reviewing",
      "Reflecting",
      "Summarizing",
      "Wrapping up",
      "Assessing",
    ],
    "fetch": [
      "Fetching URL",
      "Downloading",
      "Retrieving",
    ],
    "explain": [
      "Explaining",
      "Describing",
      "Analyzing",
      "Interpreting",
      "Documenting",
    ],
    "answer-mode": [
      "Searching",
      "Scanning codebase",
      "Finding matches",
      "Locating symbols",
      "Querying index",
      "Analyzing results",
      "Researching",
      "Gathering context",
    ],
  ]

  private let custom: [String: [String]]

  public init(projectDirectory: String? = nil) {
    if let dir = projectDirectory {
      let path = (dir as NSString).appendingPathComponent(".junco/phrases.json")
      if let data = FileManager.default.contents(atPath: path),
         let parsed = try? JSONDecoder().decode([String: [String]].self, from: data) {
        self.custom = parsed
      } else {
        self.custom = [:]
      }
    } else {
      self.custom = [:]
    }
  }

  /// Get a random phrase for a stage.
  public func phrase(for stage: String) -> String {
    let candidates = (custom[stage] ?? []) + (Self.builtin[stage] ?? Self.builtin["execute"]!)
    return candidates.randomElement() ?? "Working"
  }

  /// Get a spinner frame for the given tick count.
  public static func spinner(tick: Int) -> String {
    spinnerFrames[tick % spinnerFrames.count]
  }

  /// Format a status line with spinner + phrase.
  public func status(stage: String, tick: Int) -> String {
    "\(Self.spinner(tick: tick)) \(phrase(for: stage))"
  }

  /// Format a thinking indicator shown below the prompt in red.
  public static func thinkingIndicator(stage: String, tick: Int, phrases: ThinkingPhrases) -> String {
    let frame = spinner(tick: tick)
    let phrase = phrases.phrase(for: stage)
    return Style.red("\(frame) \(phrase)...")
  }
}
